name: Push Event Workflow

on: 
  push:
    paths:
      - 'MuNLP/**'
      - '.github/workflows/**'
      - 'requirements.txt'

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Print directory
        run: echo "Current directory: $(pwd)"

      - name: Run tests
        run: pytest
        working-directory: MuNLP
