name: Push Event Workflow

on: 
  push:
    paths:
      - 'MuNLP/**'
      - '.github/workflows/**'
jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v3
      
    - name : Install Packages 
      run : pip install -r requirements.txt
      
    - name : Run tests 
      run : pytest
